version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rifaflow-app-development
    ports:
      - "3028:3028"
    working_dir: /app
    command: sh -c "npx prisma migrate deploy && node dist/main"
    env_file:
      - .env.dev
    depends_on:
      - db
    networks:
      - rifaflow-network
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

  db:
    image: postgres:15-alpine
    container_name: rifaflow-db-development
    environment:
      - POSTGRES_USER=rifa-flow-dev
      - POSTGRES_PASSWORD=flowrifadev
      - POSTGRES_DB=rifaflow-development
    volumes:
      - raffle-back_postgres_data:/var/lib/postgresql/data
    networks:
      - rifaflow-network
    ports:
      - "5432:5433"

networks:
  rifaflow-network:
    driver: bridge

volumes:
  raffle-back_postgres_data:
  node_modules:
  app_data:
