version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile.prod
    container_name: rifaflow-app
    ports:
      - "3026:3026"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - rifaflow-network
    restart: always
    command: sh -c "./wait-for-db.sh && npx prisma migrate deploy && npm run start:prod"

  db:
    image: postgres:15-alpine
    container_name: rifaflow-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rifaflow-network
    ports:
      - "5434:5434"
networks:
  rifaflow-network:
    driver: bridge

volumes:
  postgres_data:
