version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rifaflow-dev
    ports:
      - "3030:3030"
      - "5555:5555" 
    working_dir: /app
    command: sh -c "./wait-for-db.sh && npx prisma migrate deploy && node dist/main" 
    env_file:
      - .env.dev
    depends_on:
      - db
    networks:
      - rifaflow-network
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

  db:
    image: postgres:15-alpine
    container_name: rifaflow-db-development
    environment:
      - POSTGRES_USER=flowdev
      - POSTGRES_PASSWORD=rifaflow23444
      - POSTGRES_DB=rifaflow-dev
    volumes:
      - raffle-back_postgres_data:/var/lib/postgresql/data
    networks:
      - rifaflow-network
    ports:
      - "5432:5433"

networks:
  rifaflow-network:
    driver: bridge

volumes:
  raffle-back_postgres_data:
  node_modules:
  app_data:
