version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rifaflow-app
    ports:
      - "3026:3026"
    working_dir: /app
    command: sh -c "./wait-for-db.sh && npx prisma migrate deploy && node dist/main" 
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - rifaflow-network
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

  db:
    image: postgres:15-alpine
    container_name: rifaflow-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - raffle-back_postgres_data:/var/lib/postgresql/data
    networks:
      - rifaflow-network
    ports:
      - "5434:5432"

networks:
  rifaflow-network:
    driver: bridge

volumes:
  raffle-back_postgres_data:
  node_modules:
  app_data:
