name: Deploy Raffle-flow-back

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Build and Load Docker Image
      run: |
        docker buildx build --load -t alvesr23/raffle-back:latest -f dockerfile.prod .
      
    - name: Push Docker Image  
      run: docker push alvesr23/raffle-back:latest
        
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Certifique-se de que a rede exista. Caso contrário, crie-a.
          docker network create raffle-network || true

          # Baixar a imagem mais recente
          docker pull alvesr23/raffle-back:latest

          # Parar e remover o container anterior
          docker stop raffle-back || true
          docker rm raffle-back || true

          # Executar o novo container na rede especificada
          docker run -d --name raffle-back --network raffle-network -p 3026:3000 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            -e SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
            -e SECRET=${{ secrets.SECRET }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            alvesr23/raffle-back:latest

          # Verificar se o container foi iniciado corretamente
          docker ps
