- name: Set build date
      id: date
      run: echo "BUILD_DATE=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Build and Load Docker Image
      run: |
        docker buildx build \
          --build-arg BUILD_DATE=${{ steps.date.outputs.BUILD_DATE }} \
          --no-cache \
          --load \
          -t alvesr23/raffle-back:latest \
          -t alvesr23/raffle-back:${{ steps.date.outputs.BUILD_DATE }} \
          -f dockerfile.prod .
      
    - name: Push Docker Image  
      run: |
        docker push alvesr23/raffle-back:latest
        docker push alvesr23/raffle-back:${{ steps.date.outputs.BUILD_DATE }}
        
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Pulling new image..."
          docker pull alvesr23/raffle-back:${{ steps.date.outputs.BUILD_DATE }}
          
          echo "Stopping old container..."
          docker stop raffle-back || true
          docker rm raffle-back || true

          echo "Creating network if not exists..."
          docker network create raffle-back_rifaflow-network || true
          
          echo "Starting new container..."
          docker run -d --name raffle-back \
            --network raffle-back_rifaflow-network \
            -p 3026:3000 \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
            -e SUPABASE_KEY="${{ secrets.SUPABASE_KEY }}" \
            -e SECRET="${{ secrets.SECRET }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --restart unless-stopped \
            alvesr23/raffle-back:${{ steps.date.outputs.BUILD_DATE }}

          echo "Cleaning up old images..."
          docker image prune -f

          echo "Verifying deployment..."
          docker inspect raffle-back | grep BUILD_TIME