name: Deploy Raffle-flow-back

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Build and Load Docker Image
      run: |
        docker buildx build --load -t alvesr23/raffle-back:latest -f dockerfile.prod .
      
    - name: Push Docker Image  
      run: docker push alvesr23/raffle-back:latest
        
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Copiar o arquivo .env para a VPS
          echo "${{ secrets.ENV_FILE }}" > /app/.env
          
          # Garantir que o container antigo seja removido
          docker pull alvesr23/raffle-back:latest
          docker stop raffle-back || true
          docker rm raffle-back || true

          # Rodar o container com as variáveis do arquivo .env
          docker run -d --name raffle-back -p 3026:3000 \
            --env-file /app/.env \
            alvesr23/raffle-back:latest

          # Listar os containers ativos
          docker ps
