name: Deploy Raffle-flow-back

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker Image
      run: |
        docker buildx build -t ${{ secrets.DOCKER_HUB_USERNAME }}/alvesr23/raffle-back:latest -f dockerfile.prod .
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/alvesr23/raffle-back:latest
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/alvesr23/raffle-back:latest
          docker stop raffle-back || true
          docker rm raffle-back || true
          docker run -d --rm --name raffle-back -p 3000:3000 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/alvesr23/raffle-back:latest
